[project]
name = "visionpipeline-detect-face"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "retinaface-pytorch>=0.0.7",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]
